language: bash

sudo: required

script:
    - envsubst < docker-compose.yml  > docker.2 && mv docker.2 docker-compose.yml
    - cat docker-compose.yml
    - echo ${SSH_PRIVATE_KEY} > ${HOME}/.ssh/connection.key 
    - chmod 0644 ${HOME}/.ssh/connection.key
    - ssh -i ${HOME}/.ssh/connection.key -o "StrictHostKeyChecking no"  pipeline@95.111.228.155
    - scp -o "StrictHostKeyChecking no"  -i ./connection.key  docker-compose.yml 

