language: bash

sudo: required
addons:
  ssh_known_hosts:
  - 95.111.228.155

script:
    - envsubst < docker-compose.yml  > docker.2 && mv docker.2 docker-compose.yml
    - cat docker-compose.yml
    - echo ${SSH_PRIVATE_KEY} > ${HOME}/.ssh/id_rsa
    - chmod 0400 ${HOME}/.ssh/id_rsa 
    - sudo chown -v $USER ~/.ssh/known_hosts
    - scp -o "StrictHostKeyChecking no"  ./docker-compose.yml  pipeline@95.111.228.155:/home/pipeline/
