language: bash

sudo: required

script:
    - cat docker-compose.yml
    - echo ${SSH_PRIVATE_KEY} > connection.key 
    - chmod 0644 connection.key
    - ssh -i connection.key -o "StrictHostKeyChecking no"  pipeline@95.111.228.155
    - scp -o "StrictHostKeyChecking no"  -i ./connection.key  docker-compose.yml 

